### ISSUE TITLE
输入一个值输入法就收回了

### ISSUE THREAD

**Issue by xiaominglei001** [kaxi4it/EditTextInRecyclerViewDemo#1]
如果想输入三四个值怎么办?每次都要手动点开吗?比如,现在输入框里输入一个1,输入法就折叠了,不能连续输入. 小米MIX2 MIUI9 Android7.1.1系统.

**Comment by xiaominglei001** [comment]
自己注释了获取焦点的代码,问题解决了,但不知有什么影响,目前使用起来没什么问题
`
            @Override
            public void onViewDetachedFromWindow(RecyclerView.ViewHolder holder) {
                super.onViewDetachedFromWindow(holder);
                Log.e("tag", "隐藏item=" + holder.getAdapterPosition());
                ItemHolder viewHolder = (ItemHolder) holder;
                viewHolder.et.removeTextChangedListener(textWatcher);
                //viewHolder.et.clearFocus();
//                if (etFocusPos == holder.getAdapterPosition()) {
//                   inputMethodManager.hideSoftInputFromWindow(((ItemHolder) holder).et.getWindowToken(), 0);
//                }
            }

`

**Comment by kaxi4it** [comment]
嗯，明天我看下，这个自动获取焦点意义不大，就是方便滑回来以后能继续输入，原本写了自动打开软键盘，不过被我去掉了，没加进去，因为这个主要是想说明edittext用在列表里的方法
