### ISSUE TITLE
原来的那个是什么bug？

### ISSUE THREAD

**Issue by OhPeterPan** [kaxi4it/EditTextInRecyclerViewDemo#2]
已经用了好几个地方了。。。希望说一下是什么bug，我去好好改改。。。。

**Comment by kaxi4it** [comment]
是这样的，因为原来的代码是通过 recyclerView.setItemViewCacheSize(0);，设置缓存ITEM为0，来强行让列表每次显示时，走onbindview，然后在item销毁时，去除监听等绑定事件。
但是fix的那几天发现，小米测试机上还是会有onbindview不走的情况，就导致了监听等未绑定上，
所以这次修改的思路是把缓存保持默认，只以ITEM的显示与隐藏的生命周期来设置绑定与解绑的事件，
顺便修改了edittext的焦点获取问题，改用foucschange来代替touch监听，用来解决在软键盘中按回车，切换下一个edititem时，焦点记录出错的问题。

**Comment by OhPeterPan** [comment]
好的，谢谢

**Comment by OhPeterPan** [comment]
话说大佬你的自动切换到下个输入框是如何做到的呀，我看了一圈也没找到什么特殊的设置啥的？

**Comment by kaxi4it** [comment]
我并没有做什么，他会自动找下一个输入框的焦点的，当初没这么点过，所以之前有个焦点记录错误的bug
